#!/usr/bin/env python

import argparse
import sys
from bin import get_omniprocesses, get_omnielements, reformat_csv_result, run_sf_query, delete_records
import os
from bin.settings import clr
from bin.sfdx import SalesforceCommands
from bin.versions import get_omniprocesses, get_omniprocesselements, delete_omniprocesselements, delete_omniprocesses


def check_dir():
    if not os.path.exists("bin/temp"):
        os.mkdir("bin/temp")


def add_args():
    parser = argparse.ArgumentParser(
        prog='Vlocity Clean Versions',
        description='Clean unused versions from Org and keep -n only',
    )

    parser.add_argument("-u", "--username",
                        help="Username the user you want to log in to the selected Org",
                        required=True)
    parser.add_argument("-p", "--password",
                        help="Password the user you want to log in to the selected Org",
                        required=True)
    parser.add_argument("-t", "--token",
                        help="Security Token of the user you want to log in with",
                        required=True)
    parser.add_argument("-d", "--domain",
                        help="Domain of selected Org. Provide 'test' if You try to log in to sandbox",
                        required=False)
    parser.add_argument("-o", "--object",
                        choices=['os', 'ip', 'all'],
                        help="Which objects to delete (\'os\' \'ip\' \'all\')",
                        required=True)
    parser.add_argument("-c", "--count",
                        help="Number greater greater than or equal to 0 of versions to leave on target Org excluding Activated Version",
                        required=True)

    return parser


def get_args(parser):
    result_args = {}
    args = parser.parse_args()
    result_args['username'] = args.username
    result_args['password'] = args.password
    result_args['token'] = args.token
    result_args['domain'] = args.domain
    result_args['object'] = args.object
    result_args['count'] = args.count

    return result_args


def main():
    parser = add_args()
    args = get_args(parser)  # get arguments from user command input
    check_dir()  # check directory where csv results will be saved

    sf = SalesforceCommands(username=args['username'], password=args['password'], security_token=args['token'],
                            domain=args['domain'])

    omniprocesses_df = get_omniprocesses(sf=sf, element_type=args['object'], count=args['count'])  # get omniprocess records from target Org
    delete_omniprocesses(sf=sf)
    get_omniprocesselements(sf=sf, dataframe=omniprocesses_df)
    delete_omniprocesselements(sf=sf)

    clr.print_success(">> Deleting Versions from Org ended successful")


if __name__ == '__main__':
    main()
